language: cpp

branches:
  only:
  - /.*/

dist: xenial

addons:
  apt:
    packages:
      # compilers and build tools
      - cmake-data
      - cmake
      - clang-3.8
      - cppcheck
      - g++-5
      - gcc-5
      # actual dependencies
      - libboost-dev # required
      - libboost-system-dev # required
      - libboost-filesystem-dev # required
      - libboost-program-options-dev # required
      - libclfft-dev # optional
      - libfftw3-dev # required
      - libglew-dev # optional
      - libglfw3-dev # optional
      - libhdf5-dev # optional
      - libpng++-dev # optional
      - libxrandr-dev # optional
      - ocl-icd-opencl-dev # optional

compiler: # for "matrix builds" testing various configurations
  - clang
  - gcc

env:
  global:
    - DCMAKE_BUILD_TYPE=Release
  matrix:
    - INOVESA_USE_OPENCL=0
    - INOVESA_USE_OPENCL=1
  matrix:
    -  INOVESA_USE_OPENGL=0
    -  INOVESA_USE_OPENGL=1

script: # set correct compiler versions first
  - cppcheck --quiet --error-exitcode=1 .
  - if [ "$CXX" == "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi
  - cmake -DCMAKE_BUILD_TYPE=${DCMAKE_BUILD_TYPE} .
  - cmake --build .
  - ./inovesa --buildinfo
  - ./inovesa -T 0.1 -o test.h5
  - ./inovesa -T 0.1 -i test.h5 --CollimatorRadius 0.002 --WallConductivity 3.77e7 --WallSusceptibility 2.1e-5 -o test2.png

