language: cpp

branches:
  only:
  - /.*/

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
    packages:
      # compilers and build tools
      - cmake-data
      - cmake
      - clang-3.8
      - cppcheck
      - g++-5
      - gcc-5
      # actual dependencies
      - libboost-dev # required
      - libboost-system-dev # required
      - libboost-filesystem-dev # required
      - libboost-program-options-dev # required
      - libboost-test-dev # for unit tests
#      - libclfft-dev # optional
      - libfftw3-dev # required
#      - libglew-dev # optional
#      - libglfw3-dev # optional
      - libhdf5-dev # optional
      - libpng++-dev # optional
#      - libxrandr-dev # optional
#      - opencl-dev # optional

compiler: # for "matrix builds" testing various configurations
  - clang
  - gcc

before_install:
    - pip install --user cpp-coveralls

before_install:
  - pip install --user cpp-coveralls

script: # set correct compiler versions first
  - cppcheck --quiet --error-exitcode=1 .
  - if [ "$CXX" == "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi
  - cmake -DCMAKE_BUILD_TYPE=Release -DCOVERAGE=1 .
  - cmake --build .
  - ./inovesa-test


after_success:
  - if [ "$CXX" == "g++-5" ]; then coveralls --root . -e test -e inc/Array.h -E ".*CMakeFiles.*"; fi

